version: '3'
services:
  basedatos:
    image: "mysql:8"
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - red
  etlpy:
    build: 
      context: ./SCRIPTS
    depends_on:
      - basedatos
    volumes: 
      - ./SCRIPTS:/usr/src/myapp
    networks:
      - red
    command: ./comando2.bash && python3 -u scriptpy.py
  business:
    build: 
      context: ./SCRIPTS
    volumes: 
    - ./SCRIPTS:/usr/src/myapp
    depends_on:
    - etlpy
    networks:
      - red
    command: python3 -u scriptpy2.py
    
networks:
  red:
    driver: bridge  
